### PR TITLE
Fixing SSLHandshake issue while accessing api.indix.com

### PR DESCRIPTION
**Pull request by ashwanthkumar**
- Added DST_Root_CA_X3.der cert file to the repo
- Adding the above cert to truststore and creating a SSLContext out of that, which is then used while creating the default HTTPClient.
- Added methods to plug in custom implementations of Apache's ClosableHTTPClient.

cc: @ind9/analytics @arijit-indix @praveenselvam

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
Please note still change still wouldn't work on Lolipop or any older version of Android yet.

**Comment by ashwanthkumar** [comment]
Just made some changes to make it work on Android as well. Verified it on Android level 22 - running the official Lollipop image. It needs some changes, which is also documented in the "Known issues" section of README.

**Comment by praveenselvam** [comment]
@ashwanthkumar: Thanks for this. Will work on testing it out before closing.

**Comment by bbala-github** [comment]
@ashwanthkumar shouldn't we bump up the client version as well?

**Comment by ashwanthkumar** [comment]
@bbala-github Was not sure if we're going to make any changes on top of this - that's why didn't do a client version upgrade. May be I should have been working on a SNAPSHOT version - will fix that as part of the next release.

**Pull request merged**
